---
fslogix_service_install_file: FSLogixAppsSetup.exe
fslogix_rule_editor_install_file: FSLogixAppsRuleEditorSetup.exe
fslogix_service_product_id: '{0CB0C7D0-2C12-4A78-8109-84B1535CBDBE}'
fslogix_rule_editor_product_id: '{46643030-24FC-4EEF-914B-E5F2BA19069A}'