---
- hosts: windows
  gather_facts: no


  vars_files:
    - vars/generic.yml
    - vars/deviceTRUST.yml

  tasks:

    - name: dtclient-install - Copy deviceTRUST Client
      win_copy:
        src: '../deviceTRUST/{{ devicetrust_client_install_file }}'
        dest: '{{ extract_dir }}\'

    - name: dtclient-install - Install deviceTRUST Client
      win_package:
        path: '{{ extract_dir }}\{{  devicetrust_client_install_file }}'
        product_id: '{{ devicetrust_client_product_id }}'
        arguments: /INSTALL /QUIET /NORESTART
        state: present
      register: deviceTRUST_Client_install

    - name: dtclient-install - reboot if deviceTRUST Client requires it
      win_reboot:
      when: deviceTRUST_Client_install.reboot_required

    - name: dtclient-install - Copy deviceTRUST Demo Tool
      win_copy:
        src: '../deviceTRUST/{{ devicetrust_demotool_install_file }}'
        dest: '{{ extract_dir }}\'

    - name: dtclient-install - Shortcut deviceTRUST Demo Tool
      win_shortcut:
        src: '{{ extract_dir }}\{{  devicetrust_demotool_install_file }}'
        dest: 'C:\Users\Public\Desktop\dtdemotool.lnk'
